// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compare_tasks`, `create_storage_async`, `create_task_from_map`, `evaluate_filter_expression`, `get_datetime_property`, `get_runtime`, `get_string_property`, `has_virtual_tag`, `parse_datetime`, `task_to_map`, `update_task_in_replica`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DateTimePropertyFilter`, `FilterGroup`, `NumericPropertyFilter`, `PropertyFilter`, `PropertyRef`, `SortDirection`, `SortProperty`, `StringPropertyFilter`, `TagFilter`, `TaskSort`, `VirtualTagFilter`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Get all tasks from the local TaskChampion replica as a JSON array
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
///
/// # Returns
/// JSON string containing an array of task objects
Future<String> getAllTasksJson({required String taskdbDirPath}) =>
    RustLib.instance.api.crateApiGetAllTasksJson(taskdbDirPath: taskdbDirPath);

/// Get all tasks from the local TaskChampion replica with sorting
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `sort_json` - JSON string representing the sort specification
///
/// # Returns
/// JSON string containing an array of sorted task objects
Future<String> getAllTasksWithSortJson({
  required String taskdbDirPath,
  required String sortJson,
}) => RustLib.instance.api.crateApiGetAllTasksWithSortJson(
  taskdbDirPath: taskdbDirPath,
  sortJson: sortJson,
);

/// Add a new task to the local TaskChampion replica
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `task_data` - HashMap containing task properties (description, status, priority, etc.)
///
/// # Returns
/// UUID of the newly created task as a string
Future<String> addTask({
  required String taskdbDirPath,
  required Map<String, String> taskData,
}) => RustLib.instance.api.crateApiAddTask(
  taskdbDirPath: taskdbDirPath,
  taskData: taskData,
);

/// Update an existing task in the local TaskChampion replica
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `uuid_str` - UUID of the task to update
/// * `task_data` - HashMap containing updated task properties
Future<void> updateTask({
  required String taskdbDirPath,
  required String uuidStr,
  required Map<String, String> taskData,
}) => RustLib.instance.api.crateApiUpdateTask(
  taskdbDirPath: taskdbDirPath,
  uuidStr: uuidStr,
  taskData: taskData,
);

/// Delete a task from the local TaskChampion replica
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `uuid_str` - UUID of the task to delete
///
/// # Returns
/// 0 on success, error otherwise
Future<int> deleteTask({
  required String taskdbDirPath,
  required String uuidStr,
}) => RustLib.instance.api.crateApiDeleteTask(
  taskdbDirPath: taskdbDirPath,
  uuidStr: uuidStr,
);

/// Get a single task by UUID
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `uuid_str` - UUID of the task to retrieve
///
/// # Returns
/// JSON string containing the task object, or null if not found
Future<String?> getTaskByUuid({
  required String taskdbDirPath,
  required String uuidStr,
}) => RustLib.instance.api.crateApiGetTaskByUuid(
  taskdbDirPath: taskdbDirPath,
  uuidStr: uuidStr,
);

/// Get all pending tasks from the local TaskChampion replica as a JSON array
///
/// This is optimized to use TaskChampion's built-in pending tasks query
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
///
/// # Returns
/// JSON string containing an array of pending task objects
Future<String> getPendingTasksJson({required String taskdbDirPath}) => RustLib
    .instance
    .api
    .crateApiGetPendingTasksJson(taskdbDirPath: taskdbDirPath);

/// Get tasks filtered by a filter expression
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `filter_json` - JSON string representing the filter expression
///
/// # Returns
/// JSON string containing an array of filtered task objects
Future<String> getTasksWithFilterJson({
  required String taskdbDirPath,
  required String filterJson,
}) => RustLib.instance.api.crateApiGetTasksWithFilterJson(
  taskdbDirPath: taskdbDirPath,
  filterJson: filterJson,
);

/// Get tasks filtered by a filter expression with sorting
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `filter_json` - JSON string representing the filter expression
/// * `sort_json` - JSON string representing the sort specification
///
/// # Returns
/// JSON string containing an array of filtered and sorted task objects
Future<String> getTasksWithFilterAndSortJson({
  required String taskdbDirPath,
  required String filterJson,
  required String sortJson,
}) => RustLib.instance.api.crateApiGetTasksWithFilterAndSortJson(
  taskdbDirPath: taskdbDirPath,
  filterJson: filterJson,
  sortJson: sortJson,
);

/// Synchronize tasks with a TaskChampion sync server
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `server_url` - URL of the TaskChampion sync server
/// * `client_id` - Client ID for authentication
/// * `encryption_secret` - Secret key for encrypting sync data
///
/// # Returns
/// Sync result as JSON with status and statistics
Future<SyncResultData> syncWithServer({
  required String taskdbDirPath,
  required String serverUrl,
  required String clientId,
  required String encryptionSecret,
}) => RustLib.instance.api.crateApiSyncWithServer(
  taskdbDirPath: taskdbDirPath,
  serverUrl: serverUrl,
  clientId: clientId,
  encryptionSecret: encryptionSecret,
);

/// Get the latest snapshot from the sync server
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database (not used for remote snapshots)
/// * `server_url` - URL of the TaskChampion sync server
/// * `client_id` - Client ID for authentication
/// * `encryption_secret` - Secret key for encrypting sync data
///
/// # Returns
/// JSON string containing snapshot data
Future<String> getSnapshot({
  required String taskdbDirPath,
  required String serverUrl,
  required String clientId,
  required String encryptionSecret,
}) => RustLib.instance.api.crateApiGetSnapshot(
  taskdbDirPath: taskdbDirPath,
  serverUrl: serverUrl,
  clientId: clientId,
  encryptionSecret: encryptionSecret,
);

/// Validate client credentials with the sync server
///
/// # Arguments
/// * `server_url` - URL of the TaskChampion sync server
/// * `client_id` - Client ID to validate
/// * `encryption_secret` - Secret key for encryption
///
/// # Returns
/// JSON with validation result and server information
Future<String> validateCredentials({
  required String serverUrl,
  required String clientId,
  required String encryptionSecret,
}) => RustLib.instance.api.crateApiValidateCredentials(
  serverUrl: serverUrl,
  clientId: clientId,
  encryptionSecret: encryptionSecret,
);

/// Generate a new client ID for use with the sync server
///
/// # Returns
/// New UUID as a string
Future<String> generateClientId() =>
    RustLib.instance.api.crateApiGenerateClientId();

/// Generate a new encryption secret for use with the sync server
///
/// # Returns
/// Random secret as a hex string
Future<String> generateEncryptionSecret() =>
    RustLib.instance.api.crateApiGenerateEncryptionSecret();

/// Get task database statistics
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
///
/// # Returns
/// JSON with database statistics (task count, etc.)
Future<String> getTaskdbStats({required String taskdbDirPath}) =>
    RustLib.instance.api.crateApiGetTaskdbStats(taskdbDirPath: taskdbDirPath);

/// Export all tasks to a JSON file
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `export_file_path` - Path where the export file should be saved
///
/// # Returns
/// Number of tasks exported
Future<int> exportTasks({
  required String taskdbDirPath,
  required String exportFilePath,
}) => RustLib.instance.api.crateApiExportTasks(
  taskdbDirPath: taskdbDirPath,
  exportFilePath: exportFilePath,
);

/// Import tasks from a JSON file
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `import_file_path` - Path to the JSON file to import
///
/// # Returns
/// Number of tasks imported
Future<int> importTasks({
  required String taskdbDirPath,
  required String importFilePath,
}) => RustLib.instance.api.crateApiImportTasks(
  taskdbDirPath: taskdbDirPath,
  importFilePath: importFilePath,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FilterExpression>>
abstract class FilterExpression implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TaskFilter>>
abstract class TaskFilter implements RustOpaqueInterface {
  FilterExpression get filter;

  set filter(FilterExpression filter);
}

/// Sync result structure for returning sync statistics
class SyncResultData {
  final bool success;
  final BigInt versionsSynced;
  final BigInt tasksAdded;
  final BigInt tasksUpdated;
  final BigInt tasksDeleted;
  final String? errorMessage;
  final BigInt? durationMs;

  const SyncResultData({
    required this.success,
    required this.versionsSynced,
    required this.tasksAdded,
    required this.tasksUpdated,
    required this.tasksDeleted,
    this.errorMessage,
    this.durationMs,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      versionsSynced.hashCode ^
      tasksAdded.hashCode ^
      tasksUpdated.hashCode ^
      tasksDeleted.hashCode ^
      errorMessage.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResultData &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          versionsSynced == other.versionsSynced &&
          tasksAdded == other.tasksAdded &&
          tasksUpdated == other.tasksUpdated &&
          tasksDeleted == other.tasksDeleted &&
          errorMessage == other.errorMessage &&
          durationMs == other.durationMs;
}
