// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'properties.dart';

// These functions are ignored because they are not marked as `pub`: `open_repo`

/// Get all tasks from the local TaskChampion replica as a JSON array
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
///
/// # Returns
/// JSON string containing an array of task objects
Future<String> getAllTasksJson({required String taskdbDirPath}) =>
    RustLib.instance.api.crateApiGetAllTasksJson(taskdbDirPath: taskdbDirPath);

/// Get all tasks from the local TaskChampion replica with sorting
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `sort_json` - JSON string representing the sort specification
///
/// # Returns
/// JSON string containing an array of sorted task objects
Future<String> getAllTasksWithSortJson({
  required String taskdbDirPath,
  required String sortJson,
}) => RustLib.instance.api.crateApiGetAllTasksWithSortJson(
  taskdbDirPath: taskdbDirPath,
  sortJson: sortJson,
);

/// Add a new task to the local TaskChampion replica
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `task_data` - HashMap containing task properties (description, status, priority, etc.)
///
/// # Returns
/// UUID of the newly created task as a string
Future<String> addTask({
  required String taskdbDirPath,
  required Map<String, String> taskData,
}) => RustLib.instance.api.crateApiAddTask(
  taskdbDirPath: taskdbDirPath,
  taskData: taskData,
);

/// Update an existing task in the local TaskChampion replica
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `uuid_str` - UUID of the task to update
/// * `task_data` - HashMap containing updated task properties
Future<void> updateTask({
  required String taskdbDirPath,
  required String uuidStr,
  required Map<String, String> taskData,
}) => RustLib.instance.api.crateApiUpdateTask(
  taskdbDirPath: taskdbDirPath,
  uuidStr: uuidStr,
  taskData: taskData,
);

/// Delete a task from the local TaskChampion replica
///
/// Marks the task as deleted (sets its status to `Deleted`).
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `uuid_str` - UUID of the task to delete
Future<void> deleteTask({
  required String taskdbDirPath,
  required String uuidStr,
}) => RustLib.instance.api.crateApiDeleteTask(
  taskdbDirPath: taskdbDirPath,
  uuidStr: uuidStr,
);

/// Get a single task by UUID
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `uuid_str` - UUID of the task to retrieve
///
/// # Returns
/// JSON string containing the task object, or null if not found
Future<String?> getTaskByUuid({
  required String taskdbDirPath,
  required String uuidStr,
}) => RustLib.instance.api.crateApiGetTaskByUuid(
  taskdbDirPath: taskdbDirPath,
  uuidStr: uuidStr,
);

/// Get tasks filtered by a filter expression with sorting
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `filter_json` - JSON string representing the filter expression
/// * `sort_json` - JSON string representing the sort specification
///
/// # Returns
/// JSON string containing an array of filtered and sorted task objects
Future<String> getTasksWithFilterAndSortJson({
  required String taskdbDirPath,
  required String filterJson,
  required String sortJson,
}) => RustLib.instance.api.crateApiGetTasksWithFilterAndSortJson(
  taskdbDirPath: taskdbDirPath,
  filterJson: filterJson,
  sortJson: sortJson,
);

/// Get all tasks as typed DTOs.
///
/// Prefer this over [`get_all_tasks_json`] when the Dart side can consume
/// `TaskDto` values directly: it avoids the JSON round-trip and preserves
/// tag/UDA structure exactly.
Future<List<TaskDto>> getAllTasksDtos({required String taskdbDirPath}) =>
    RustLib.instance.api.crateApiGetAllTasksDtos(taskdbDirPath: taskdbDirPath);

/// Add a task from a typed DTO. Returns the new task's UUID as a string.
Future<String> addTaskDto({
  required String taskdbDirPath,
  required TaskDto dto,
}) => RustLib.instance.api.crateApiAddTaskDto(
  taskdbDirPath: taskdbDirPath,
  dto: dto,
);

/// Replace an existing task's mutable fields from a typed DTO.
Future<void> updateTaskDto({
  required String taskdbDirPath,
  required String uuidStr,
  required TaskDto dto,
}) => RustLib.instance.api.crateApiUpdateTaskDto(
  taskdbDirPath: taskdbDirPath,
  uuidStr: uuidStr,
  dto: dto,
);

/// Synchronize tasks with a TaskChampion sync server
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `server_url` - URL of the TaskChampion sync server
/// * `client_id` - Client ID for authentication
/// * `encryption_secret` - Secret key for encrypting sync data
///
/// # Returns
/// Sync result as JSON with status and statistics
Future<SyncResultData> syncWithServer({
  required String taskdbDirPath,
  required String serverUrl,
  required String clientId,
  required String encryptionSecret,
}) => RustLib.instance.api.crateApiSyncWithServer(
  taskdbDirPath: taskdbDirPath,
  serverUrl: serverUrl,
  clientId: clientId,
  encryptionSecret: encryptionSecret,
);

/// Get the latest snapshot from the sync server
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database (not used for remote snapshots)
/// * `server_url` - URL of the TaskChampion sync server
/// * `client_id` - Client ID for authentication
/// * `encryption_secret` - Secret key for encrypting sync data
///
/// # Returns
/// JSON string containing snapshot data
Future<String> getSnapshot({
  required String taskdbDirPath,
  required String serverUrl,
  required String clientId,
  required String encryptionSecret,
}) => RustLib.instance.api.crateApiGetSnapshot(
  taskdbDirPath: taskdbDirPath,
  serverUrl: serverUrl,
  clientId: clientId,
  encryptionSecret: encryptionSecret,
);

/// Validate client credentials with the sync server
///
/// # Arguments
/// * `server_url` - URL of the TaskChampion sync server
/// * `client_id` - Client ID to validate
/// * `encryption_secret` - Secret key for encryption
///
/// # Returns
/// JSON with validation result and server information
Future<String> validateCredentials({
  required String serverUrl,
  required String clientId,
  required String encryptionSecret,
}) => RustLib.instance.api.crateApiValidateCredentials(
  serverUrl: serverUrl,
  clientId: clientId,
  encryptionSecret: encryptionSecret,
);

/// Get task database statistics
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
///
/// # Returns
/// JSON with database statistics (task count, etc.)
Future<String> getTaskdbStats({required String taskdbDirPath}) =>
    RustLib.instance.api.crateApiGetTaskdbStats(taskdbDirPath: taskdbDirPath);

/// Export all tasks to a JSON file
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `export_file_path` - Path where the export file should be saved
///
/// # Returns
/// Number of tasks exported
Future<int> exportTasks({
  required String taskdbDirPath,
  required String exportFilePath,
}) => RustLib.instance.api.crateApiExportTasks(
  taskdbDirPath: taskdbDirPath,
  exportFilePath: exportFilePath,
);

/// Import tasks from a JSON file
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `import_file_path` - Path to the JSON file to import
///
/// # Returns
/// Number of tasks imported
Future<int> importTasks({
  required String taskdbDirPath,
  required String importFilePath,
}) => RustLib.instance.api.crateApiImportTasks(
  taskdbDirPath: taskdbDirPath,
  importFilePath: importFilePath,
);

/// Retrieve distinct values for a given task property
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `property` - Name of the property to query (e.g. "description", "due")
/// * `filter_json` - Optional JSON describing a TaskFilter to limit the tasks
/// * `sort_json` - Optional JSON describing a TaskSort that may affect the order of the returned list
///
/// # Returns
/// JSON string containing an array of distinct property values
Future<List<String>> getTaskPropertyValues({
  required String taskdbDirPath,
  required String property,
  String? filterJson,
  String? sortJson,
}) => RustLib.instance.api.crateApiGetTaskPropertyValues(
  taskdbDirPath: taskdbDirPath,
  property: property,
  filterJson: filterJson,
  sortJson: sortJson,
);

/// Retrieve distinct tag values from tasks, with optional virtual tag inclusion and pattern filtering.
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `filter_json` - Optional JSON describing a TaskFilter to limit the tasks
/// * `include_virtual_tags` - When true, include virtual tags (tags starting with '+' or '-')
/// * `pattern` - Optional case-insensitive substring that a tag must contain
///
/// # Returns
/// JSON string containing an array of distinct tag values
Future<List<String>> getTags({
  required String taskdbDirPath,
  String? filterJson,
  required bool includeVirtualTags,
  String? pattern,
}) => RustLib.instance.api.crateApiGetTags(
  taskdbDirPath: taskdbDirPath,
  filterJson: filterJson,
  includeVirtualTags: includeVirtualTags,
  pattern: pattern,
);

/// Retrieve distinct property values with typed conversion.
///
/// This is a typed version of `get_task_property_values` that converts the
/// returned values to the requested type (String, DateTime, TaskStatus,
/// or TaskPriority).
///
/// # Arguments
/// * `taskdb_dir_path` - Path to the directory containing the task database
/// * `property` - Name of the property to query (e.g. "description", "due", "status")
/// * `return_type` - The type of values expected
/// * `filter_json` - Optional JSON describing a TaskFilter to limit the tasks
/// * `sort_json` - Optional JSON describing a TaskSort that may affect the order
///
/// # Returns
/// JSON string containing an array of typed property values
Future<List<String>> getTaskPropertyValuesTyped({
  required String taskdbDirPath,
  required String property,
  required PropertyReturnType returnType,
  String? filterJson,
  String? sortJson,
}) => RustLib.instance.api.crateApiGetTaskPropertyValuesTyped(
  taskdbDirPath: taskdbDirPath,
  property: property,
  returnType: returnType,
  filterJson: filterJson,
  sortJson: sortJson,
);

/// Retrieve all possible enum values for a given property type.
///
/// Only supports `EnumStatus` and `EnumPriority`. For any other return type,
/// returns an error.
///
/// # Arguments
/// * `return_type` - The type of enum values to return
///
/// # Returns
/// JSON string containing an array of all possible enum values
Future<List<String>> getAllEnumValues({
  required PropertyReturnType returnType,
}) => RustLib.instance.api.crateApiGetAllEnumValues(returnType: returnType);
