// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -990271282;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'tc_helper',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  FilterExpression crateApiTaskFilterAutoAccessorGetFilter({
    required TaskFilter that,
  });

  void crateApiTaskFilterAutoAccessorSetFilter({
    required TaskFilter that,
    required FilterExpression filter,
  });

  Future<String> crateApiAddTask({
    required String taskdbDirPath,
    required Map<String, String> taskData,
  });

  Future<int> crateApiDeleteTask({
    required String taskdbDirPath,
    required String uuidStr,
  });

  Future<int> crateApiExportTasks({
    required String taskdbDirPath,
    required String exportFilePath,
  });

  Future<String> crateApiGenerateClientId();

  Future<String> crateApiGenerateEncryptionSecret();

  Future<String> crateApiGetAllTasksJson({required String taskdbDirPath});

  Future<String> crateApiGetAllTasksWithSortJson({
    required String taskdbDirPath,
    required String sortJson,
  });

  Future<String> crateApiGetPendingTasksJson({required String taskdbDirPath});

  Future<String> crateApiGetSnapshot({
    required String taskdbDirPath,
    required String serverUrl,
    required String clientId,
    required String encryptionSecret,
  });

  Future<String?> crateApiGetTaskByUuid({
    required String taskdbDirPath,
    required String uuidStr,
  });

  Future<String> crateApiGetTaskdbStats({required String taskdbDirPath});

  Future<String> crateApiGetTasksWithFilterAndSortJson({
    required String taskdbDirPath,
    required String filterJson,
    required String sortJson,
  });

  Future<String> crateApiGetTasksWithFilterJson({
    required String taskdbDirPath,
    required String filterJson,
  });

  Future<int> crateApiImportTasks({
    required String taskdbDirPath,
    required String importFilePath,
  });

  Future<SyncResultData> crateApiSyncWithServer({
    required String taskdbDirPath,
    required String serverUrl,
    required String clientId,
    required String encryptionSecret,
  });

  Future<void> crateApiUpdateTask({
    required String taskdbDirPath,
    required String uuidStr,
    required Map<String, String> taskData,
  });

  Future<String> crateApiValidateCredentials({
    required String serverUrl,
    required String clientId,
    required String encryptionSecret,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FilterExpression;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FilterExpression;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FilterExpressionPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TaskFilter;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TaskFilter;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_TaskFilterPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  FilterExpression crateApiTaskFilterAutoAccessorGetFilter({
    required TaskFilter that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskFilter(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFilterExpression,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTaskFilterAutoAccessorGetFilterConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskFilterAutoAccessorGetFilterConstMeta =>
      const TaskConstMeta(
        debugName: "TaskFilter_auto_accessor_get_filter",
        argNames: ["that"],
      );

  @override
  void crateApiTaskFilterAutoAccessorSetFilter({
    required TaskFilter that,
    required FilterExpression filter,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskFilter(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFilterExpression(
            filter,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTaskFilterAutoAccessorSetFilterConstMeta,
        argValues: [that, filter],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskFilterAutoAccessorSetFilterConstMeta =>
      const TaskConstMeta(
        debugName: "TaskFilter_auto_accessor_set_filter",
        argNames: ["that", "filter"],
      );

  @override
  Future<String> crateApiAddTask({
    required String taskdbDirPath,
    required Map<String, String> taskData,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskdbDirPath, serializer);
          sse_encode_Map_String_String_None(taskData, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAddTaskConstMeta,
        argValues: [taskdbDirPath, taskData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAddTaskConstMeta => const TaskConstMeta(
    debugName: "add_task",
    argNames: ["taskdbDirPath", "taskData"],
  );

  @override
  Future<int> crateApiDeleteTask({
    required String taskdbDirPath,
    required String uuidStr,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskdbDirPath, serializer);
          sse_encode_String(uuidStr, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_8,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDeleteTaskConstMeta,
        argValues: [taskdbDirPath, uuidStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteTaskConstMeta => const TaskConstMeta(
    debugName: "delete_task",
    argNames: ["taskdbDirPath", "uuidStr"],
  );

  @override
  Future<int> crateApiExportTasks({
    required String taskdbDirPath,
    required String exportFilePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskdbDirPath, serializer);
          sse_encode_String(exportFilePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExportTasksConstMeta,
        argValues: [taskdbDirPath, exportFilePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportTasksConstMeta => const TaskConstMeta(
    debugName: "export_tasks",
    argNames: ["taskdbDirPath", "exportFilePath"],
  );

  @override
  Future<String> crateApiGenerateClientId() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGenerateClientIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateClientIdConstMeta =>
      const TaskConstMeta(debugName: "generate_client_id", argNames: []);

  @override
  Future<String> crateApiGenerateEncryptionSecret() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGenerateEncryptionSecretConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateEncryptionSecretConstMeta =>
      const TaskConstMeta(
        debugName: "generate_encryption_secret",
        argNames: [],
      );

  @override
  Future<String> crateApiGetAllTasksJson({required String taskdbDirPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskdbDirPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetAllTasksJsonConstMeta,
        argValues: [taskdbDirPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetAllTasksJsonConstMeta => const TaskConstMeta(
    debugName: "get_all_tasks_json",
    argNames: ["taskdbDirPath"],
  );

  @override
  Future<String> crateApiGetAllTasksWithSortJson({
    required String taskdbDirPath,
    required String sortJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskdbDirPath, serializer);
          sse_encode_String(sortJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetAllTasksWithSortJsonConstMeta,
        argValues: [taskdbDirPath, sortJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetAllTasksWithSortJsonConstMeta =>
      const TaskConstMeta(
        debugName: "get_all_tasks_with_sort_json",
        argNames: ["taskdbDirPath", "sortJson"],
      );

  @override
  Future<String> crateApiGetPendingTasksJson({required String taskdbDirPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskdbDirPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetPendingTasksJsonConstMeta,
        argValues: [taskdbDirPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetPendingTasksJsonConstMeta =>
      const TaskConstMeta(
        debugName: "get_pending_tasks_json",
        argNames: ["taskdbDirPath"],
      );

  @override
  Future<String> crateApiGetSnapshot({
    required String taskdbDirPath,
    required String serverUrl,
    required String clientId,
    required String encryptionSecret,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskdbDirPath, serializer);
          sse_encode_String(serverUrl, serializer);
          sse_encode_String(clientId, serializer);
          sse_encode_String(encryptionSecret, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetSnapshotConstMeta,
        argValues: [taskdbDirPath, serverUrl, clientId, encryptionSecret],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetSnapshotConstMeta => const TaskConstMeta(
    debugName: "get_snapshot",
    argNames: ["taskdbDirPath", "serverUrl", "clientId", "encryptionSecret"],
  );

  @override
  Future<String?> crateApiGetTaskByUuid({
    required String taskdbDirPath,
    required String uuidStr,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskdbDirPath, serializer);
          sse_encode_String(uuidStr, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetTaskByUuidConstMeta,
        argValues: [taskdbDirPath, uuidStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetTaskByUuidConstMeta => const TaskConstMeta(
    debugName: "get_task_by_uuid",
    argNames: ["taskdbDirPath", "uuidStr"],
  );

  @override
  Future<String> crateApiGetTaskdbStats({required String taskdbDirPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskdbDirPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetTaskdbStatsConstMeta,
        argValues: [taskdbDirPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetTaskdbStatsConstMeta => const TaskConstMeta(
    debugName: "get_taskdb_stats",
    argNames: ["taskdbDirPath"],
  );

  @override
  Future<String> crateApiGetTasksWithFilterAndSortJson({
    required String taskdbDirPath,
    required String filterJson,
    required String sortJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskdbDirPath, serializer);
          sse_encode_String(filterJson, serializer);
          sse_encode_String(sortJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetTasksWithFilterAndSortJsonConstMeta,
        argValues: [taskdbDirPath, filterJson, sortJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetTasksWithFilterAndSortJsonConstMeta =>
      const TaskConstMeta(
        debugName: "get_tasks_with_filter_and_sort_json",
        argNames: ["taskdbDirPath", "filterJson", "sortJson"],
      );

  @override
  Future<String> crateApiGetTasksWithFilterJson({
    required String taskdbDirPath,
    required String filterJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskdbDirPath, serializer);
          sse_encode_String(filterJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetTasksWithFilterJsonConstMeta,
        argValues: [taskdbDirPath, filterJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetTasksWithFilterJsonConstMeta =>
      const TaskConstMeta(
        debugName: "get_tasks_with_filter_json",
        argNames: ["taskdbDirPath", "filterJson"],
      );

  @override
  Future<int> crateApiImportTasks({
    required String taskdbDirPath,
    required String importFilePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskdbDirPath, serializer);
          sse_encode_String(importFilePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImportTasksConstMeta,
        argValues: [taskdbDirPath, importFilePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImportTasksConstMeta => const TaskConstMeta(
    debugName: "import_tasks",
    argNames: ["taskdbDirPath", "importFilePath"],
  );

  @override
  Future<SyncResultData> crateApiSyncWithServer({
    required String taskdbDirPath,
    required String serverUrl,
    required String clientId,
    required String encryptionSecret,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskdbDirPath, serializer);
          sse_encode_String(serverUrl, serializer);
          sse_encode_String(clientId, serializer);
          sse_encode_String(encryptionSecret, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_result_data,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSyncWithServerConstMeta,
        argValues: [taskdbDirPath, serverUrl, clientId, encryptionSecret],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWithServerConstMeta => const TaskConstMeta(
    debugName: "sync_with_server",
    argNames: ["taskdbDirPath", "serverUrl", "clientId", "encryptionSecret"],
  );

  @override
  Future<void> crateApiUpdateTask({
    required String taskdbDirPath,
    required String uuidStr,
    required Map<String, String> taskData,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskdbDirPath, serializer);
          sse_encode_String(uuidStr, serializer);
          sse_encode_Map_String_String_None(taskData, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUpdateTaskConstMeta,
        argValues: [taskdbDirPath, uuidStr, taskData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateTaskConstMeta => const TaskConstMeta(
    debugName: "update_task",
    argNames: ["taskdbDirPath", "uuidStr", "taskData"],
  );

  @override
  Future<String> crateApiValidateCredentials({
    required String serverUrl,
    required String clientId,
    required String encryptionSecret,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverUrl, serializer);
          sse_encode_String(clientId, serializer);
          sse_encode_String(encryptionSecret, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiValidateCredentialsConstMeta,
        argValues: [serverUrl, clientId, encryptionSecret],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiValidateCredentialsConstMeta =>
      const TaskConstMeta(
        debugName: "validate_credentials",
        argNames: ["serverUrl", "clientId", "encryptionSecret"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FilterExpression => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFilterExpression;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FilterExpression => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFilterExpression;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TaskFilter => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskFilter;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TaskFilter => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskFilter;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  FilterExpression
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFilterExpression(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FilterExpressionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TaskFilter
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskFilter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TaskFilterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TaskFilter
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskFilter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TaskFilterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TaskFilter
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskFilter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TaskFilterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  FilterExpression
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFilterExpression(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FilterExpressionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TaskFilter
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskFilter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TaskFilterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_i_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  SyncResultData dco_decode_sync_result_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SyncResultData(
      success: dco_decode_bool(arr[0]),
      versionsSynced: dco_decode_u_64(arr[1]),
      tasksAdded: dco_decode_u_64(arr[2]),
      tasksUpdated: dco_decode_u_64(arr[3]),
      tasksDeleted: dco_decode_u_64(arr[4]),
      errorMessage: dco_decode_opt_String(arr[5]),
      durationMs: dco_decode_opt_box_autoadd_u_64(arr[6]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  FilterExpression
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFilterExpression(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FilterExpressionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TaskFilter
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskFilter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TaskFilterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TaskFilter
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskFilter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TaskFilterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TaskFilter
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskFilter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TaskFilterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  FilterExpression
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFilterExpression(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FilterExpressionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TaskFilter
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskFilter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TaskFilterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  int sse_decode_i_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt8();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  SyncResultData sse_decode_sync_result_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_versionsSynced = sse_decode_u_64(deserializer);
    var var_tasksAdded = sse_decode_u_64(deserializer);
    var var_tasksUpdated = sse_decode_u_64(deserializer);
    var var_tasksDeleted = sse_decode_u_64(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    var var_durationMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    return SyncResultData(
      success: var_success,
      versionsSynced: var_versionsSynced,
      tasksAdded: var_tasksAdded,
      tasksUpdated: var_tasksUpdated,
      tasksDeleted: var_tasksDeleted,
      errorMessage: var_errorMessage,
      durationMs: var_durationMs,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFilterExpression(
    FilterExpression self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FilterExpressionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskFilter(
    TaskFilter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TaskFilterImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskFilter(
    TaskFilter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TaskFilterImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskFilter(
    TaskFilter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TaskFilterImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFilterExpression(
    FilterExpression self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FilterExpressionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskFilter(
    TaskFilter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TaskFilterImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt8(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_sync_result_data(
    SyncResultData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_u_64(self.versionsSynced, serializer);
    sse_encode_u_64(self.tasksAdded, serializer);
    sse_encode_u_64(self.tasksUpdated, serializer);
    sse_encode_u_64(self.tasksDeleted, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
    sse_encode_opt_box_autoadd_u_64(self.durationMs, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class FilterExpressionImpl extends RustOpaque implements FilterExpression {
  // Not to be used by end users
  FilterExpressionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FilterExpressionImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_FilterExpression,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_FilterExpression,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_FilterExpressionPtr,
  );
}

@sealed
class TaskFilterImpl extends RustOpaque implements TaskFilter {
  // Not to be used by end users
  TaskFilterImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TaskFilterImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_TaskFilter,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_TaskFilter,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_TaskFilterPtr,
  );

  FilterExpression get filter =>
      RustLib.instance.api.crateApiTaskFilterAutoAccessorGetFilter(that: this);

  set filter(FilterExpression filter) => RustLib.instance.api
      .crateApiTaskFilterAutoAccessorSetFilter(that: this, filter: filter);
}
