// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A single annotation entry.
class AnnotationDto {
  /// RFC-3339 timestamp of when the annotation was added.
  final String entry;

  /// The free-form annotation text.
  final String description;

  const AnnotationDto({required this.entry, required this.description});

  @override
  int get hashCode => entry.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnnotationDto &&
          runtimeType == other.runtimeType &&
          entry == other.entry &&
          description == other.description;
}

/// Sync result structure for returning sync statistics.
///
/// (Renamed candidate `SyncResult` is tracked under ticket R9; the public
/// name is preserved here for FFI backward compatibility.)
class SyncResultData {
  final bool success;
  final BigInt versionsSynced;
  final BigInt tasksAdded;
  final BigInt tasksUpdated;
  final BigInt tasksDeleted;
  final String? errorMessage;
  final BigInt? durationMs;

  const SyncResultData({
    required this.success,
    required this.versionsSynced,
    required this.tasksAdded,
    required this.tasksUpdated,
    required this.tasksDeleted,
    this.errorMessage,
    this.durationMs,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      versionsSynced.hashCode ^
      tasksAdded.hashCode ^
      tasksUpdated.hashCode ^
      tasksDeleted.hashCode ^
      errorMessage.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResultData &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          versionsSynced == other.versionsSynced &&
          tasksAdded == other.tasksAdded &&
          tasksUpdated == other.tasksUpdated &&
          tasksDeleted == other.tasksDeleted &&
          errorMessage == other.errorMessage &&
          durationMs == other.durationMs;
}

/// A fully typed task, intended to replace the lossy `HashMap<String,String>`
/// representation at the FFI boundary.
///
/// Notable fixes vs. the legacy map encoding:
/// * `tags` is a real `Vec<String>` — the old code joined/split on
///   whitespace, which corrupted tags containing spaces (ticket R5).
/// * `udas` is a separate map, so a UDA whose name happens to share a prefix
///   with a built-in property (e.g. `"entry_note"`) is no longer silently
///   dropped (ticket R5 / I-13).
/// * `annotations` is a structured list rather than `annotation_<timestamp>`
///   keys interleaved with everything else.
///
/// Datetimes are carried as RFC-3339 strings to stay wire-compatible with
/// the existing Dart consumers without forcing a chrono-aware FRB regen.
///
/// Field groups:
/// * **Identity** — `uuid`. Generated on create; read-only on update (the
///   update path addresses the task by a separately-passed uuid and ignores
///   this field entirely).
/// * **Settable built-ins** — `description`, `status`, `priority`, `due`,
///   `wait`, `entry`, `modified`, `end`, `tags`, `depends`, `annotations`.
/// * **Promoted UDA fields** — `scheduled`, `until`, `recur`. These have no
///   dedicated TaskChampion setter and are stored as conventional UDAs of the
///   same name (Taskwarrior convention). They are first-class DTO fields so
///   callers do not need to know they are UDAs in storage; they must NOT also
///   appear in `udas` when writing (the apply functions skip any `udas` key
///   that matches a promoted field so nothing is double-written).
///
/// Read-only columns (id, imask, mask, parent, urgency, component) are
/// intentionally NOT settable inputs here; they surface on read through
/// `udas` / existing getters.
///
/// `#[serde(default)]` keeps JSON deserialization of older payloads (which
/// predate `scheduled`/`until`/`recur`) working; the derived [`Default`]
/// backs it.
class TaskDto {
  /// Task uuid. Generated server-side on create; READ-ONLY on update (the
  /// update path ignores this field entirely).
  final String uuid;
  final String description;
  final TaskStatusDto status;

  /// Canonical priority code (`"H"`/`"M"`/`"L"`) or `None` for no priority.
  /// See [`crate::properties::CANONICAL_PRIORITIES`].
  final String? priority;

  /// RFC-3339 due date, if set.
  final String? due;

  /// RFC-3339 wait-until date, if set.
  final String? wait;

  /// RFC-3339 creation timestamp, if set.
  final String? entry;

  /// RFC-3339 last-modified timestamp, if set. When absent on update the
  /// library-managed value is left alone (commit refreshes it anyway).
  final String? modified;

  /// RFC-3339 completion/deletion timestamp, if set. Stored via the generic
  /// property setter so an explicit value round-trips (normally `end` is
  /// derived from status changes).
  final String? end;

  /// RFC-3339 scheduled-start timestamp, if set. Stored as the conventional
  /// "scheduled" UDA.
  final String? scheduled;

  /// RFC-3339 until/expiry timestamp, if set. Stored as the conventional
  /// "until" UDA.
  final String? until;

  /// Recurrence rule/duration string (e.g. `"weekly"`), if set. Stored as
  /// the conventional "recur" UDA — there is no dedicated
  /// TaskChampion setter.
  final String? recur;

  /// User tags. Each tag is a separate element; spaces are preserved.
  final List<String> tags;

  /// Dependency UUIDs (string form).
  final List<String> depends;

  /// Annotations, oldest-first.
  ///
  /// * `Some(list)` — replace the task's annotations with exactly this list
  ///   (an empty `Some(vec![])` clears all annotations).
  /// * `None` — leave the task's existing annotations untouched.
  final List<AnnotationDto>? annotations;

  /// User-defined attributes, keyed by their Taskwarrior name.
  ///
  /// Keys matching a promoted field (`scheduled`/`until`/`recur`) are
  /// owned by those dedicated fields: the dedicated field wins on write,
  /// and an absent dedicated field clears the stored UDA. Such keys in
  /// this map are therefore ignored — use the dedicated fields instead.
  final Map<String, String> udas;

  const TaskDto({
    required this.uuid,
    required this.description,
    required this.status,
    this.priority,
    this.due,
    this.wait,
    this.entry,
    this.modified,
    this.end,
    this.scheduled,
    this.until,
    this.recur,
    required this.tags,
    required this.depends,
    this.annotations,
    required this.udas,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      description.hashCode ^
      status.hashCode ^
      priority.hashCode ^
      due.hashCode ^
      wait.hashCode ^
      entry.hashCode ^
      modified.hashCode ^
      end.hashCode ^
      scheduled.hashCode ^
      until.hashCode ^
      recur.hashCode ^
      tags.hashCode ^
      depends.hashCode ^
      annotations.hashCode ^
      udas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskDto &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          description == other.description &&
          status == other.status &&
          priority == other.priority &&
          due == other.due &&
          wait == other.wait &&
          entry == other.entry &&
          modified == other.modified &&
          end == other.end &&
          scheduled == other.scheduled &&
          until == other.until &&
          recur == other.recur &&
          tags == other.tags &&
          depends == other.depends &&
          annotations == other.annotations &&
          udas == other.udas;
}

/// Mirrors [`taskchampion::Status`] for FFI consumers.
///
/// Stored as the lowercase Taskwarrior string in the wire form so the Dart
/// side matches the rest of the crate's vocabulary.
enum TaskStatusDto {
  pending,
  completed,
  deleted,
  recurring,

  /// TaskChampion's escape hatch for unknown status strings.
  unknown,
}
