// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Sync result structure for returning sync statistics
class SyncResultData {
  final bool success;
  final BigInt versionsSynced;
  final BigInt tasksAdded;
  final BigInt tasksUpdated;
  final BigInt tasksDeleted;
  final String? errorMessage;
  final BigInt? durationMs;

  const SyncResultData({
    required this.success,
    required this.versionsSynced,
    required this.tasksAdded,
    required this.tasksUpdated,
    required this.tasksDeleted,
    this.errorMessage,
    this.durationMs,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      versionsSynced.hashCode ^
      tasksAdded.hashCode ^
      tasksUpdated.hashCode ^
      tasksDeleted.hashCode ^
      errorMessage.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResultData &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          versionsSynced == other.versionsSynced &&
          tasksAdded == other.tasksAdded &&
          tasksUpdated == other.tasksUpdated &&
          tasksDeleted == other.tasksDeleted &&
          errorMessage == other.errorMessage &&
          durationMs == other.durationMs;
}
