// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The type of values expected from a property query.
enum PropertyReturnType {
  /// Return raw string values.
  string,

  /// Return RFC-3339 datetime strings that can be parsed as DateTime.
  dateTime,

  /// Return task status enum values.
  enumStatus,

  /// Return task priority enum values.
  enumPriority,
}
